dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      # moto has not implemented the bucket_inventory_configuration yet, so the CI test fails while running pytest.  The test passes when run against an actual AWS account.  We need to remove the following PYTEST_ARGS filter when moto catches up.
      script: make mockstack/pytest PYTEST_ARGS="-k 'not create_bucket_inventory'"
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-s3-bucket
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-s3-bucket v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-s3-bucket/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: k+5h3Y5yirAA+9yLEYfJz+L1SxVlEYXfltBfciovbWNEMXe+by5POAfZA3C7PUMSO2OBUMGzixsMZeUHS+aPfMRNqICQBCtzWjdcFdUjFxvnYMFekw1wecotRAkCMG8E1fU4T05LWoBgOkMbaKhVuAWkx18C5OWVCCJNNggO7+xg2+V5ovTt4pmSuKJw5y6DkS0Ltw4Su19HkeQ6YBZYUqtoRG67+tKbel8uWVFAFDcziXb27UDGWYfmv+y0iEE6A10qmq/Aj+fZVqQYGsSEOtu6e5MsWEvu75uqEM7jEGyXFTUHDLo58l8u9FMOQDuhQOY2w/Txk4HVmt+qaC9KUQH6zcHgCHzBau7A/4dSgye3W54fc6F+35hVnBCfk/XENh2Yv3GfeHt9G2+IK5dwEBrPPN3zJF4iEw4RIIvy6kSyLBNQ4BhgpW5Vr7JDRh42R+0EfeCO+U+dX4vBO/ZnIL6ABfJyg2oW9lDJ7Vaylrme2y5FpKypGFmjpsIpaMIkBd2S7fSXqrhs9MMRezWnC9kJzTar9RYq1nMwyj9FWGq3MzkWcS0jp/Zj3uvUZvnXZHeZLoA8PtJhENbbTYVIO8OcW1L4MQnaQGYnpXixsdH3kupZaamiIECbnazR5HpaEaHJn44QmuSQuqsKHSfLoXfFL+8kyCbGo/9OA7OV2cM=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-s3-bucket
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
